#!/usr/bin/env bash
# Bash script with the minimum number of commands that Nginx run on port 80
sudo rm /etc/nginx/sites-enabled/default
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
