#!/usr/bin/env bash
# It displays "To infinity and beyond indefinitely and sends msg
# on receiving a SIGTERM signal
trap "echo I am invincible!!!" SIGTERM
while true; do
	echo To infinity and beyond
	sleep 2
done
