#!/usr/bin/env bash
#  Bash script that configures an Ubuntu server with the below requirements.
# Change localhost to 127.0.0.2
# Change facebook.com to 8.8.8.8

cp /etc/hosts ~/hosts.new
echo "127.0.0.1		hosts.new" > ~/localhost
echo "157.240.22.35	facebook.com" >> ~/localhost
cp -f ~/localhost /etc/hosts
