#!/usr/bin/env bash
#  Bash script that configures an Ubuntu server with the below requirements.
# Change localhost to 127.0.0.2
# Change facebook.com to 8.8.8.8
sudo cp /etc/hosts /etc/hosts.bak

# Modify the /etc/hosts file to replace the localhost and Facebook entries
sudo sed -i -e 's/^127\.0\.0\.1\s*localhost/127.0.0.2 localhost/' \
           -e 's/^.*\bfacebook\.com\b/69.63.176.13 facebook.com/' \
           /etc/hosts
